import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./features/**/*.{ts,tsx}",
    "./hooks/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Stitch Custom Colors
        "text-primary": "#171717",
        "on-secondary-fixed": "#0c1f1a",
        "on-primary-container": "#858383",
        "on-tertiary-container": "#868381",
        "border-subtle": "#E8E2D8",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "tertiary-container": "#1d1b1a",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "on-tertiary-fixed-variant": "#484645",
        "secondary-container": "#cfe5dc",
        "on-tertiary-fixed": "#1d1b1a",
        "surface": "#fdf8f8",
        "on-error-container": "#93000a",
        "surface-card": "#FFFFFF",
        "on-tertiary": "#ffffff",
        "on-surface": "#1c1b1b",
        "surface-variant": "#e5e2e1",
        "tertiary": "#000000",
        "surface-container-high": "#ebe7e6",
        "surface-container": "#f1edec",
        "surface-container-low": "#f7f3f2",
        "secondary-fixed-dim": "#b6cbc3",
        "pastel-blue": "#D9ECF6",
        "pastel-yellow": "#F8E7A8",
        "surface-bright": "#fdf8f8",
        "page-bg": "#DDECEA",
        "surface-dim": "#ddd9d8",
        "inverse-on-surface": "#f4f0ef",
        "on-secondary-fixed-variant": "#374b44",
        "tertiary-fixed-dim": "#cac6c3",
        "surface-main": "#FCFAF5",
        "inverse-surface": "#313030",
        "tertiary-fixed": "#e6e1df",
        "primary-container": "#1c1b1b",
        "outline-variant": "#c4c7c7",
        "shell-bg": "#F7F4EC",
        "outline": "#747878",
        "pastel-pink": "#F6DCE8",
        "primary-fixed": "#e5e2e1",
        "on-error": "#ffffff",
        "on-secondary-container": "#536760",
        "mint-strong": "#BFE8D7",
        "on-surface-variant": "#444748",
        "inverse-primary": "#c8c6c5",
        "text-secondary": "#6F6F6F",
        "secondary-fixed": "#d2e7df",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "pastel-lavender": "#E7E0FA",
        "pastel-orange": "#F6DFC8",
        "text-soft": "#9A9A9A",
        "on-primary": "#ffffff",
        "on-background": "#1c1b1b",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "DEFAULT": "0.25rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "page-padding": "32px",
        "shell-padding": "20px",
        "card-gap": "16px",
        "sidebar-width": "84px",
        "section-gap": "24px"
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Arial", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        button: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        "heading-lg": ["Plus Jakarta Sans", "sans-serif"],
        "heading-md": ["Plus Jakarta Sans", "sans-serif"],
        "heading-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "button": ["14px", { lineHeight: "1", fontWeight: "600" }],
        "label": ["12px", { lineHeight: "1", fontWeight: "600" }],
        "display": ["42px", { lineHeight: "1.15", fontWeight: "700" }],
        "heading-lg": ["30px", { lineHeight: "1.2", fontWeight: "700" }],
        "heading-md": ["22px", { lineHeight: "1.3", fontWeight: "700" }],
        "heading-sm": ["18px", { lineHeight: "1.35", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
